name: Deploy JhonathanOS

on:
  push:
    branches:
      - main  # <--- VERIFICA: Si tu rama se llama 'master', cambia 'main' por 'master'

permissions:
  contents: write  # Esto le da permiso al robot para publicar en gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Crear archivo config.js
        run: |
          echo "${{ secrets.FIREBASE_CONFIG }}" > config.js

      - name: Desplegar a GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages