name: Deploy JhonathanOS

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Generar archivos de configuración
        run: |
          # Eliminamos para evitar conflictos
          rm -f config.js
          
          # Creamos el archivo como un script puro (el navegador lo ama)
          # Esto inyecta el JSON del secreto directamente en una variable global
          echo "window.firebaseConfig = ${{ secrets.FIREBASE_CONFIG }};" > config.js
          
          touch .nojekyll
          sed -i '/config.js/d' .gitignore || true
          
          echo "Debug: Primeras lineas del archivo generado:"
          head -n 1 config.js

      - name: Desplegar a GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
          clean: true