name: Deploy JhonathanOS

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Generar archivos de configuración
        run: |
          # Usamos window.firebaseConfig para que sea accesible desde cualquier script
          echo "window.firebaseConfig = ${{ secrets.FIREBASE_CONFIG }};" > config.js
          touch .nojekyll
          sed -i '/config.js/d' .gitignore || true
          
          echo "Verificando existencia:"
          ls -la config.js .nojekyll

      - name: Desplegar a GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
          clean: true